# Generated by Django 3.2.8 on 2021-12-25 11:21

from django.db import migrations, models
import registrationjwt2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=registrationjwt2.models.code_generator)),
                ('email', models.EmailField(blank=True, max_length=400, null=True, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Inactive'), (2, 'Activated')], default=1)),
            ],
        ),
    ]
